### ISSUE TITLE
rack example broken

### ISSUE THREAD

**Issue by dancinglightning** [opal/opal#1020]
The rack example includes an index.html.erb, but does not in fact use it.

Since there is no readme and it states in other places that this index approach is the way to go, it seems natural for a beginner to assume the index.html.erb generates the loaded page.

It does not, as the title of the page gives away.

Some digging reveals that one has to set the index_path to the index file name and that this has been changed in 0.6!!

**Comment by vais** [comment]
@dancinglightning could you send a PR to fix this please?

**Comment by dancinglightning** [comment]
Hi Vais,
maybe we can later talk on gitter (maybe with elia).
I had thought about sending the fix, but this is really a project culture issue. I mean this is not a bug so much as a "i don't care", especially given the amount of these documentation issues i've been running into.
So i don't really want to clean up after, but if there is a project census, i would be willing to help with documentation. As i say this is not documentation but part of the a developers work of changing the server, writing the server (which has 0 lines of comments, meaning **i don't care about you**, deal with it.) (ps not you personally off course, i know you do)

**Comment by vais** [comment]
Well, @dancinglightning, this project is as much *yours* as it is mine :wink: The only difference is the number of hours put in so far (all of which I put in for no other reason than to learn and have fun, and specifically *not* to deliver *a product* for anyone - I do enough of that *at work*). So, there's no one else to do this stuff if not you, me, and any other *you-me*'s (new word!) who care to join in.

This is my personal opinion, I am *not* an owner of this project. @adambeynon, @meh, and @elia may have other things to say on this matter, but my sense is, if you feel something needs to be done, you're probably just going to have to do it, or it will not get done. Unless you are lucky and someone else feels the same way, has the time to do it, and does it for you.

:beers:

**Comment by dancinglightning** [comment]
@vais Is that what they call a euphemism (i'm not english). This is certainly not my project, i don't even have commit rights.
This https://github.com/rubyclerks/ or this https://github.com/salama/ are projects i own / run, and assume responsibility for, because i wrote them.

These issues are a way a newbie can participate. And your rebuff is a way to stop newbies from wanting to.

So do you want to chat and what can be done? Or just close this ?

**Comment by elia** [comment]
I do care, but lack the time. The project could use some documentation help. For the examples the best thing I can think about is to fail the build if they're outdated. 

As for what @vais said I agree 100% in the sense that everyone does its best and no one has any obligations. 

Also let me say that any conclusion about people's intentions drawn from some code is probably inaccurate.

**Comment by dancinglightning** [comment]
@elia i have heard you and vais care about documentation, and that is why i suggested we chat. Because only when you see the problem (not just symptoms) can you address it.

Lack of time is never a reason, only ever an excuse. Imagine you want to go somewhere, and you can take the car or walk. Walking will be slower. You might not have the time to walk.
But the direction is not influenced by which mode of transport.
In the same way it is with tests and documentation. If you see them as your goal, you will do them.
If they are not your goal they will not happen. Because you did something else. With your time. 

So you do you want to chat and start making a change ?

**Comment by Ajedi32** [comment]
I think what @dancinglightning is trying to say is that he believes the problems with documentation in Opal are systemic. E.g. Not enough emphasis is being given on updating documentation as part of the development process, therefore the docs will always be outdated. Is that correct, @dancinglightning?

If so, I'm not sure I agree the problem is that widespread. Relatively speaking, I think the docs for Opal are already pretty decent, and they could be made great with a little extra help. I don't think you can conclude the problem is as serious as you seem to be implying based solely on this issue and #997 (unless there's a lot more that I'm missing?).

Also, I think documentation written as part of the learning process for a new user or contributor is actually potentially more valuable than documentation written as part of the development process by Opal developers. If you're finding problems with the documentation @dancinglightning while learning to use Opal, then IMO you're the perfect candidate for writing the documentation designed to help others like you. Opal developers are already very familiar with the project, so it's harder for them to put themselves in the shoes of a new user of the platform when they're writing documentation. (@vais's contributions to [CONTRIBUTING.md](https://github.com/opal/opal/blob/master/CONTRIBUTING.md) are the perfect example of this.)

**Comment by Ajedi32** [comment]
Also, just a suggestion, but I think it's worth noting that when you're new to a project, going to the project maintainers / management / coworkers / whoever claiming that the project has systemic problems and demanding change usually isn't well received, regardless of whether or not you're right. I've found that a much better approach is to instead being to instigate change yourself, a little at a time. Point out the specific problems you see, then work to help resolve them. That approach tends to be more constructive and gives much better results, from what I've seen.

**Comment by elia** [comment]
Yes, I confirm that the "i don't care about you" is a bit off putting and unjust, whoever wrote whatever code did care enough to write the said code. I'm grateful there's an example folder with actual example code that I can use [and fix](https://github.com/opal/opal/commit/1fb1d45be7602f1e24d42fc338ee510af45834c0) if I have the time to do so.

@dancinglightning help is accepted in any form (in fact this issue will stay open until the index thing it's fixed), the most effective is of course subitting a PR (to which anyone "has access") and I'd be more than happy to give commit access to a frequent contributor. I'm also actively looking for someone that can improve the docs story for Opal, that's the plan for 0.9 anyway.

**Comment by dancinglightning** [comment]
Well i was obviously slightly upset yesterday, sorry.
The pr is #1022 
I'll close this attempt at communication gone wrong.

**Comment by elia** [comment]
Respect 👍🏼
