### ISSUE TITLE
Hash#to_n doesn't handle JS values

### ISSUE THREAD

**Issue by jgaskins** [opal/opal#1244]
I tried porting part of the [`asciify-me` Inesita app](https://github.com/inesita-rb/asciify-me) to Clearwater. One of the things I'm trying to do is:

```ruby
class VideoOutput
  # ...
  def render
    video(src: webcam.stream)
  end
end
```

But `webcam.stream` is not a Ruby object; it's an instance of a JavaScript `MediaStream`. When that attributes hash gets `to_n` called on it, it raises an exception because JS objects don't respond to `respond_to?`.

Is there a way we can detect whether the value is a Ruby object and leave it alone if not? I thought at one point there was an `$$is_ruby` or `$$is_opal` property on the prototype of all Ruby `Object` descendants, but I might be remembering a conversation about it and not actual code. :-)

**Comment by iliabylich** [comment]
@jgaskins Opal has a method `Kernel#native?`:
``` ruby
module Kernel
  def native?(value)
    `value == null || !value.$$class`
  end
end
```
i.e. `null` gets converted to a `nil` (and it's native by default) and all objects having a property `$$class` (which gets populated when opal calls `allocate`)
 [Here](http://opalrb.org/try/?code:native_obj%20%3D%20%60%7B%20%27key%27%20%3A%20%27value%27%20%7D%60%0Awrapped_obj%20%3D%20Native(native_obj)%0A%0Aputs%20native%3F(native_obj)%0Aputs%20native%3F(wrapped_obj)) is a small example.

By the way, I think it should be
``` ruby
src = `window.URL.createObjectURL(stream)`
vide(src: src)
```
instead of `webcam.stream`

**Comment by jgaskins** [comment]
Thanks for the tip. We may want to modify `Hash#to_n` to use that. Here's a reproduction of the error: http://opalrb.org/try/?code:hash%20%3D%20%7B%0A%20%20foo%3A%20%60%7B%7D%60%2C%0A%7D%0Anative%20%3D%20hash.to_n

> By the way, I think it should be … instead of `webcam.stream`

I appreciate the heads up, but my webcam object already encapsulates that. ;-)

**Comment by iliabylich** [comment]
@jgaskins Yeah, all recursive structures have this issue, for example `Array`:
``` ruby
a = [`{}`]
a.to_n
```
[This place](https://github.com/opal/opal/blob/master/stdlib/native.rb#L495) contains the bug. I suppose it should be something like
``` ruby
%x{
  result.push(#{Native.try_convert(obj)});
}
```
