### ISSUE TITLE
Regression "Reopening a class adds new methods to subclasses"

### ISSUE THREAD

**Issue by vais** [opal/opal#1245]
[This PR](https://github.com/opal/opal/pull/1243) added a few more specs to run, and (as a result?) the ["Reopening a class adds new methods to subclasses"](https://github.com/ruby/rubyspec/blob/master/language/class_spec.rb#L233-L242) spec started failing and had to be [filtered out](https://github.com/opal/opal/blob/master/spec/filters/bugs/language.rb#L125) from the spec suite. I suspect there's some global interference at play here, since there was no code changed, just more code being executed.

**Comment by iliabylich** [comment]
[This](https://github.com/ruby/rubyspec/blob/master/core/unboundmethod/arity_spec.rb#L7-L9) evaluate:
``` ruby
evaluate("def m(); end")
```

Invokes inside [this](https://github.com/ruby/mspec/blob/master/lib/mspec/runner/evaluate.rb#L44-L45) `instance_eval`:
``` ruby
evaluator.instance_eval(ruby)
evaluator.instance_eval(&block)
```
where evaluator is actually a `Module`

Let's try what happens when you call `eval`/`instance_eval` on a module:
``` ruby
if RUBY_ENGINE == "opal"
  require 'opal-parser'
end

Module.new do
  eval          "def a_method; puts 'from eval inside a Module'; end"
  instance_eval "def a_method2; puts 'from instance_eval inside a Module'; end"
end

Object.new.a_method rescue nil
123.a_method rescue nil


Object.new.a_method2 rescue nil
123.a_method2 rescue nil
```

MRI: blank output
Opal:
```
from eval inside a Module
from eval inside a Module
from instance_eval inside a Module
from instance_eval inside a Module
```
This method becomes globally accessible (looks like `eval` gets called on a `Kernel`). Not sure if it's a know issue.

btw, there are some other tests in rubyspec that use `eval` (for example, [this one](https://github.com/ruby/rubyspec/blob/master/core/module/module_function_spec.rb#L262-L274)). For me this spec is green (just like on CI), but it breaks [another spec](https://github.com/ruby/rubyspec/blob/master/core/module/attr_writer_spec.rb#L6-L12), and seems I'm the only one who has this issue (probably it's somehow related to the platform-specific tests order)

**Comment by elia** [comment]
I suspect this has been fixed in 0-9-stable, if anyone can confirm I'll close it, in the meanwhile it's moved to the 0.10 milestone.
