### ISSUE TITLE
`break` does not break out of more than one level deep

### ISSUE THREAD

**Issue by vais** [opal/opal#1247]
```ruby
def m1(&block)
  yield
  'm1'
end

p(m1{break 42})
```
Result in Opal: `42`, same as MRI.

Let's add more levels:
```ruby
def m2
  yield
  'm2'
end

def m1(&block)
  m2 &block
  'm1'
end

p(m1{break 42})
```
Result in Opal: `"m1"`
Result in MRI: `42`

**Comment by meh** [comment]
Yeah, sadly this is a problem that is really hard to fix without adding `try/catch` everywhere on the call stack.

I thought about how to solve it various times but I never got a decent idea, on top of that the compiler would need a redesign because you'd need to know the outer calls where a `break` might kick-in and change every call-site. So we'd need a multi-pass compiler, or at least having an initial pass that gathers all `break`s.

**Comment by vais** [comment]
@meh I thought so... Well, let it henceforth be a *known issue* :sparkles:

**Comment by eregon** [comment]
Would it work if there was a try/catch only around call sites which have a block containing a break?
It would indeed require to detect the break and associate that with the call site before emitting the final JS (hacky idea: maybe there can be some code patching to add the try/catch around when seeing the break if you really want to avoid multiple passes?).
```ruby
ret = foo.bar(:a, :b)
`call foo.bar(:a. :b)`

ret = foo.bar { break 42 }
`try { call foo.bar($block) } catch ($breaker) { ... }`
```
The insight is `break` needs to be lexically in the call site block, otherwise it's just a different behavior (error for procs, like `return` for a lambda).

**Comment by meh** [comment]
@eregon yeah, that would work, but it would need a redesign of the compiler, I don't think it's possible with how it's currently designed.

**Comment by elia** [comment]
isn't it very similar to returning from a block in a method?

    $ opal --no-exit -Oce 'def foo; bar { return :bak }; end'

```js
/* Generated by Opal 0.8.1 */
(function(Opal) {
  Opal.dynamic_require_severity = "error";
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$bar']);
  return (Opal.Object.$$proto.$foo = function() {try {

    var $a, $b, TMP_1, self = this;

    return ($a = ($b = self).$bar, $a.$$p = (TMP_1 = function(){var self = TMP_1.$$s || this;

    Opal.ret("baz")}, TMP_1.$$s = self, TMP_1), $a).call($b);
    } catch ($returner) { if ($returner === Opal.returner) { return $returner.$v } throw $returner; }
  }, nil) && 'foo'
})(Opal);
```

**Comment by elia** [comment]
Maybe (for both the `returner` and the `breaker`) a stack or id system should be added but I think the current compiler can do that. 

@meh am I missing something?

**Comment by meh** [comment]
@elia maybe you're right, I just can't find where the logic for that is, the `Opal.ret` stuff is compiled in `nodes/logic.rb`, but I can't find where it does the call-site change.

**Comment by elia** [comment]
laid out some work in #1250, please @meh (or anyone) have a look, there's a bunch of failing specs but both of the following examples work:

```rb
def m2
  yield
  'm2'
end

def m1(&block)
  m2 &block
  'm1'
end

p(m1{break 42}) # => 42
```

```rb
p loop { loop { break 123 } } # => 123
```

**Comment by eregon** [comment]
@elia The second example should just break from the inner but not outer `loop`, right?

**Comment by elia** [comment]
@eregon you're right, need to fix it, probably I need to take the first iter scope instead of the top one [here](https://github.com/opal/opal/pull/1250/files#diff-43f53868b54dc943426937f6b0767ec5R48)

**Comment by vais** [comment]
:tada: :sparkles:
