### ISSUE TITLE
Add Auto Optimization/Benchmark Check

### ISSUE THREAD

**Issue by wied03** [opal/opal#1255]
In order to keep track of which methods are optimize-able by JS runtimes, do something like this:

https://gist.github.com/wied03/76cb79e6076e48eee9a5

Probably need to focus on only methods in corelib as the "superset" to test against.

Key points from Gitter:
- Use text based output (not HTML reports)
- Fail the build (use Travis here) if new unoptimized methods appear
- Have a white list of class#method items that are "allowed" to be not optimized, and fail the build if a class#method that's not on that list is not optimized. This would catch regressions, and would force one to add a class#method to the list explicitly if there's no other way to implement the method. This would also let us track progress on optimization, as the list gets shorter over time.
- Might need each method check to run in its own process. The reason I mention it is that functions can get deoptimized for being too polymorphic. For example, if you call a function with more than some VM-specific number of different types of arguments (pretty sure in Safari it's 4, might be 3 in Chrome), it can decide to deoptimize the function because the cost (both performance and memory) of optimizing it for each different type of argument potentially outweighs the performance you gain from it.

**Comment by iliabylich** [comment]
@wied03 Travis clones the main `opal` repo and switches to the post-merge branch (which becomes available in `FETCH_HEAD`). I guess the code should look like:
``` sh
git checkout master
# report 1
BENCH_NAME=master rake bench
get checkout FETCH_HEAD
# report 2
BENCH_NAME=pr rake bench
BENCHES=master,pr rake bench:compare
```

As I know, Travis runs everything in Docker containers. So it becomes possible for one docker image to affect performance of another container on the same physical server, right?

One more thing about reporting. Text-based report is the only way to get a response from Travis, but its output may become huge. Any thoughts about it?

How should we proceed with some cases when `klass#method` was fast, but incomplete, and after implementing it completely we get some performance regression (which is required due to new complexity)?

**Comment by wied03** [comment]
@iliabylich - Probably don't need to worry about Docker performance for this. It's less about benchmarking time and more about an "optimization check." I've updated the issue title to be more clear.

As to text output, eventually the output would be quite small (because everything will either pass or be ignored), so not sure that's a problem. It will also probably only need to run on a set of corelib methods.

For the above reasons, not sure if we need to worry about other branches & Travis. I would think we fail the main build alongside the the rubyspecs, etc. if something fails and is not whitelisted. @vais or @meh might have opinions here.

**Comment by meh** [comment]
The plan is fine as is as far as I'm concerned.

**Comment by vais** [comment]
:+1:
