### ISSUE TITLE
Arity Regression from 0.9 to 0.10

### ISSUE THREAD

**Issue by wied03** [opal/opal#1424]
It's great that a lot of args stuff is supported now. That said, since then, arity broke in several cases.

On 0.10 master
Execute: `bundle exec opal foo.rb`
Response:
```
arity
1
```

On 0.9 with same command line:
```
arity
0
```
foo.rb code:
```ruby
dummy = Class.new
class_method = dummy.method(:new)
puts 'arity'
puts class_method.arity
```

No surprise here. Since restargs is being used to implement splat stuff for the `Class` `new(*args, &block)` method, it broke.

Old: `Opal.defn(self, '$new', TMP_2 = function() {`
New: `Opal.defn(self, '$new', TMP_2 = function($a_rest) {`

**Comment by wied03** [comment]
I think the new approach is sensible (passing params explicitly rather than using the function object). That said. I think we need to get arity checking in gear though so it doesn't break like this.

Approach:
1. `Method#arity` becomes a noop (or throws exception) if not compiled with arity checking enabled
2. When arity checking is enabled, pass in the MRI style `parameters` info into `Opal.defn`
3. Modify `Opal.defn` etc. to take in an optional params parameter that the compiler drops in and set that (and arity) on the function object such that `Method` can pick it up.

Thoughts?

**Comment by elia** [comment]
The proposed approach makes sense to me.

```js
  (Opal.defn(Opal.Object, '$foo', TMP_1 = [-2, [["req","a"],["opt","b"],["rest","c"]]], function ːfoo(a, b, $a_rest) {
    …
    var $arity = TMP_1[0]; …
  }), nil) && 'foo'
```
cc @iliabylich

**Comment by wied03** [comment]
@elia @iliabylich - so that it doesn't silently produce bad results, any problem with using throws/raise in those methods when arity is off? I can't think of why someone would call those arity methods unless they are testing (e.g. RSpec).

**Comment by iliabylich** [comment]
@wied03 Well, one more regression caused by https://github.com/opal/opal/pull/1412 :smile: . I was trying to join the functionality of method params and block params in `NodeWithArg` class. Why do we need this parameter `$a_rest`? Because blocks expand their arguments when a single array item is provided (like `proc { |a,b| [a,b] }.call([1,2]) == [1,2]`). And of course it changes `function.length` for the method body. I'd say that we still need these `$*_rest arguments, instead we should modify `Method#arity`.

However, I'm not sure that your approach is correct. `Method#arity` is not related to `Method#parameters` (simply because arity can be negative). I'd propose the following:
1. Method body should always be identified when arity checking is enabled.
2. We have a code that calculates arity [right here](https://github.com/opal/opal/blob/master/lib/opal/nodes/def.rb#L133-L160) and calculated value **is correct**.
3. According to [Proc#arity](https://github.com/opal/opal/blob/master/opal/corelib/proc.rb#L66-L70) we should assign `$arity` property to identified function

I'll try to fix it this evening, don't have any time atm.

**Comment by iliabylich** [comment]
@elia What do you think about raising an exception from `Proc#arity` if arity checking is disabled?

**Comment by wied03** [comment]
@iliabylich - Don't worry, I understand why you made the change. 

Although `parameters` is a nice to have and just arity would do just fine, I'm fairly sure you can derive the arity number from `parameters`. On MRI, `parameters` tells you:
* how many params there are
* whether they are required or not
* whether it's a rest args case
* whether it's a keyword required arg

The params look really close to the compiler's args anyways (see elia comment).

Isn't that all you need to derive arity? Tools like rspec like to work with `parameters` but they're fine with arity.

**Comment by iliabylich** [comment]
@wied03 I was trying to explain that `parameters` are not related directly to `arity` :smile: . By the way, almost finished with arity, 4 specs are failing locally from `ruby/spec/core/method/arity_spec.rb`.

**Comment by wied03** [comment]
I'm still trying to understand what you're saying. How are those not directly related?

In any case, it's great that you're working on arity. Keep up the good work!

**Comment by elia** [comment]
> @elia What do you think about raising an exception from Proc#arity if arity checking is disabled?

@iliabylich no problem, the only concern is for stuff out there that could break, the right place for the raising implementation probably being `corelib/unsupported.rb`.

**Comment by iliabylich** [comment]
@wied03 Could you check this issue again with latest master?

**Comment by wied03** [comment]
https://travis-ci.org/opal/opal-rspec/jobs/121575337 - it got worse

**Comment by wied03** [comment]
In the middle of something now but might be able to check later

**Comment by iliabylich** [comment]
@wied03 That's strange. There are around 50 passing specs from `ruby/spec` (only method_missing works incorrectly with `arity` and `parameters`). Did you enable arity check? Anyway, even if it's disabled it still should not fail, instead it should return blank array if no `$$parameters` available (https://github.com/opal/opal/pull/1425/files#diff-c80c5d7d6ba478fead3a333c4aa80753R109). Also just realized that it might be related to dynamically generated methods. I'll take a look at this issue tomorrow

**Comment by wied03** [comment]
@iliabylich - Yep. Arity is enabled for opal-rspec by default on >= 0.10. The code that's failing is when RSpec tries to take a `Method` object and interrogate the parameters.
