### ISSUE TITLE
Javascript Map for Hash?

### ISSUE THREAD

**Issue by wied03** [opal/opal#1471]
I swear the reasons for this are documented somewhere but I couldn't find them so maybe this will make it easier to find after someone replies.

Why/why not use the `Map` object in ES5 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map to power the `Hash` class?

If the reason is only compatibility and we think it might be more performant to use this, maybe we ought to introduce ES5/ES6/ES7 optimization flags where you can pick your compile target?

**Comment by elia** [comment]
_Could have been a chat on gitter or irc._

Anyway the reason is that the semantics are quite different as Ruby relies on the `#hash` method on objects to _hash_ them. With regard to that it could only be useful to use numbers instead of strings as hash-table keys as MRI does. But in order to do that we would need to add another compilation (ES5 → ES3) step just for that very tiny bit of consistency with MRI. Which makes it not worth the effort. 🙂

**Comment by wied03** [comment]
What if you did a to_s on the hash of a key when accessing/putting? How would that result in an additional compilation step (if you had an --es5/6 flag of sorts)?

**Comment by elia** [comment]
@wied03 no, it's runtime, and using plain JS objects gives a nice speedup for String/Symbol keys for which we skip the call to `String#hash` and just use the raw object as key

**Comment by wied03** [comment]
Got it. I had never really looked at `hash.rb` before.
