### ISSUE TITLE
Integer("0") raises an ArgumentError

### ISSUE THREAD

**Issue by Ontonator** [opal/opal#1549]
I'm running Opal v0.10.1 and, just as the title says, running `Integer("0")` raises an `ArgumentError`. Looking into the generated source, it seems that Opal is interpreting the zero as a base flag for base 8, removing it (after setting the base to 8) and then trying to convert the remaining empty string to an integer.

**Comment by Ontonator** [comment]
This code should work as a temporary fix if placed in the script to be compiled.

```ruby
module Kernel
  alias_method :old_Integer, :Integer
  def Integer(*args)
    str = args.first
    str == "0" ? 0 : old_Integer(*args)
  end
end
```

**Comment by vais** [comment]
Good catch, @Ontonator, looks like we're missing something like this:
```
  it "returns zero for a string consisting of a single zero character" do
    Integer("0").should == 0
  end
```
somewhere [around here in Ruby Spec](https://github.com/ruby/spec/blob/master/core/kernel/Integer_spec.rb#L173). Would you be interested in submitting a pull request to [Ruby Spec](https://github.com/ruby/spec)?

In Opal, [this is the line of code responsible for this issue](https://github.com/opal/opal/blob/master/opal/corelib/kernel.rb#L876) 😊 

We could fix this by inserting something like `if (value === "0") return 0;` [at this point in our code](https://github.com/opal/opal/blob/master/opal/corelib/kernel.rb#L855). Looks like "0" is a special case, because any other string that starts with a "0" should be interpreted as octal. Would you be interested in submitting a pull request to Opal? 😸
