### ISSUE TITLE
Accessing nested modules?

### ISSUE THREAD

**Issue by camertron** [opal/opal#1554]
I can't figure out how to access a nested module after loading an Opal-compiled file. Here's the ruby code:

``` ruby
module Foo
  module Bar
    class Baz
      def initialize
        puts "Init, wahoo"
      end
    end
  end
end
```

I tried to load the code in a node REPL and access the `Baz` class:

``` javascript
$> var Opal = require('/path/to/test.js');
$> Opal.Opal.Foo.Bar  // => undefined
```

So obviously I have no idea what I'm doing. A few questions:
1. How do I load and use opal-generated code in node and/or the browser? Opal doesn't appear to have exported any modules - what's the story here?
2. Why can't I access the `Baz` class? The few examples I've seen online seem to do it by simply dotting their way down the module hierarchy.

Thanks in advance for helping out an opal n00b.

**Comment by elia** [comment]
> 1. How do I load and use opal-generated code in node and/or the browser? Opal doesn't appear to have exported any modules - what's the story here?

Opal replicates Ruby and thus all constants (i.e. classes & modules) are globals. When you have access to the `Opal` property on the global object you have everything you need (in your example would be `var Opal = require('/path/to/test.js').Opal;`.

> 2. Why can't I access the Baz class? The few examples I've seen online seem to do it by simply dotting their way down the module hierarchy.

I think that semi-hidden feature is just kinda broken in recent versions, I remember fixing it for some cases some months ago but probably the tests weren't enough (I'll leave this issue open just for that). Anyway a better way to query for constants is to use `Opal.Object.$const_get('Foo::Bar::Baz');` that is guaranteed to work properly

> Thanks in advance for helping out an opal n00b.

Welcome!
Consider also asking things on gitter.im/opal/opal or just come over there to say 👋🏼

**Comment by camertron** [comment]
Awesome, thanks @elia! That totally worked :)

**Comment by radanskoric** [comment]
Hi, although this was closed I don't think the issue is resolved. I ran into the exact same issue. After reading "Ruby from JavaScript" section of [the official documentation](http://opalrb.com/docs/guides/v0.11.0/compiled_ruby.html) I was expecting that in the example given here `Opal.Foo.Bar.Baz` would work. Especially since nesting the class in just one module works as expected.

I think either the documentation needs to be extended or it needs to be treated as a bug and be fixed.

I would be happy to create a PR for either of those (change documentation or change behaviour) as long as someone more experienced with Opal can make a decision on what should be done and also point me in the right direction (especially with regards to fixing the behaviour since I'm unfamiliar with Opal inner code structure).  :)

**Comment by camertron** [comment]
@radanskoric yeah I probably shouldn't have closed this guy. Just reopened. Hopefully that'll get it on the maintainers' radar.

**Comment by elia** [comment]
@radanskoric good call, the documentation should be updated. If it makes sense from the newcomer's perspective (please help me on this) it should retain the tip clearly stating the version where it's applicable. 

The problem with `Opal.Foo.Bar.Baz` is that `Opal.Foo` returns the object contained in the `Foo` constant, in order to make this work `Foo` should contain a `@Bar` instance variable.

To resolve both problems (ease of access and less hackery) the [proposed solution](https://github.com/opal/opal/pull/1668) is to use `$$` and make it look like `Opal.$$.Foo.$$.Bar.$$.Baz` probably only working for locally defined constants (i.e. no constants inherited from an `include`) and slightly resembling `::` (`::Foo::Bar::Baz`). Leaving to `$const_get` the heavy lifting.

Top level constants should stay accessible via `Opal.`, so far I can't think of a problem with that.

_Please add your own feedback/considerations on this stuff, a fresh perspective is especially important to me._
