### ISSUE TITLE
Remove strange `variable interpolation` support from Opal?

### ISSUE THREAD

**Issue by zw963** [opal/opal#1679]
Following is a example:

```rb
def initialize(time=0)
    @interval = `setInterval(function(){#{yield}}, time)`
end
```

As a skilled ruby programmer, less surprise in almost all case, except this.

This behavior cause lots of gems relative to Opal to use this strange usage
deeply. e.g.  [opal-irb](https://github.com/fkchang/opal-irb), 

Fine, I think this method context seem like same as really javascript context.
if raise a error told `time`  is missing, maybe not the really case within the javascript
context, but, I still consider following keep string interpolation is better:

```rb
def initialize(time=0)
    @interval = `setInterval(function(){#{yield}}, #{time})`
end
```

**Comment by iliabylich** [comment]
You can use both versions because `time` is registered as a local variable in Opal's "runtime" (so you can use it in you Ruby code, no matter interpolated or not) and it's defined as a `time` JS variable.

I would even say that it's good that it works this way because it brings more flexibility. But the second versions looks better for me because in case of error it raises a Ruby-specific exception.

Closing. There's nothing to fix or change, that's just the way Opal works.

**Comment by zw963** [comment]
@iliabylich, Thanks.

That OK for me, though i think we should add you's explain to README for clarify.
