### ISSUE TITLE
redo in "unterminated" while is not working

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1816]
## Reproduction case with "unterminated" while

Let's consider the following code:

**redo.rb**
```rb
count = 0
while true
  p 'a'
  count += 1
  if count == 1
    redo
  end
  p 'b'
  break;
end
```

**MRI (Ruby 2.4.1)**

```
ruby redo.rb 
"a"
"a"
"b"
````

**Opal master**

```
bundle exec opal redo.rb
"a"
"b"
````

As you can see `redo` was "ignored" and the second "a" letter is missing.
The generated code is:

```js
count = 0;
$a = false; while ($a || $truthy(true)) {$a = false;
    
  self.$p("a");
  count = $rb_plus(count, 1);
  if (count['$=='](1)) {
    $a = true};
  self.$p("b");
  break;;
};
```

Instead of calling the loop again, the code is changing the value of `$a` to `true`.

## Working example with for loop

Please note that if we replace the "unterminated" while loop by a for loop then it's working:

**redo-loop.rb**
```rb
count = 0
(0..5).each do |i|
  p 'a'
  count += 1
  if count == 1
    redo
  end
  p 'b'
  break;
end
```
```
bundle exec opal redo-loop.rb             
"a"
"a"
"b"
```

In this case the generated code looks fine (with a `TMP_1` function called on `redo`). Here's a simplified version of the generated code:

```js
$send($range(0, 5, false), 'each', [], (TMP_1 = function (i) {
  this.$p("a");
  count = $rb_plus(count, 1);
  if (count['$=='](1)) {
    return TMP_1.apply(null, $slice.call(arguments))
  }
  this.$p("b");
  Opal.brk(nil, Opal.new_brk());
}));
```

**Comment by iliabylich** [comment]
"redo" in the block works because we wrap the block body into the function and we know its name, so we can re-run it again (`TMP_1.apply(...)`). But for the while loop we generate a simple JS `while` loop, so we can't easily re-execute current iteration. It could be technically solved by wrapping the whole body of the while loop into a function (`while_f` or something like this, so compiler loop will be something like `while_f = function() { ... }; while(cond) { while_f() }`) and so `redo` could be compiled to `while_f()`.

But. `while` loops (just like `for` loops) do not introduce a new closure, so every variable defined in the loop is available outside:
``` ruby
a = 1

while true do
  p "Entering with #{a}"
  a += 1
  redo if a < 3
  b = 100
  break
end

p "a = #{a}"
p "b = #{b}"
```

```
$ ruby test2.rb
"Entering with 1"
"Entering with 2"
"a = 3"
"b = 100"
```

It's also not a problem, but it requires some coding, take a look at the `for_rewriter` that handles `for` loops like `for i in [1, 2, 3] do; ...; end`:
1. it grabs all local variable declarations in the `for` loop
2. defines them outside of the loop
3. converts definitions (like `local variable declare` nodes) to the `local variables get `nodes`
4. and finally converts it to the block like `[1, 2, 3].each do |i| ... end`

It allows us later to "fool" the compiler and force it to declare all variables outside of the loop.

So, for example:
``` ruby
for i in [1, 2, 3] do
  j = 1
  k = 2
end
```
becomes:
``` ruby
i = nil # loop variable
j = nil # variable declared in the loop
k = nil # variable declared in the loop
[1, 2, 3].each do |i|
  j = 1
  k = 2
end
```

We could use the same technic here and wrap any while body to the function.

I have absolutely no time atm, so I'll be able to take a look at this issue only next week. Feel free to ping me here or on the gitter if you need any help. Basically, what you need it is a subset of the `ForRewriter` functionality for collecting variables inside the body of the loop + injecting their declarations to the AST **before** the loop (`lvars_declared_in_body` and `outer_assigns`)

**Comment by mojavelinux** [comment]
> But for the while loop we generate a simple JS while loop, so we can't easily re-execute current iteration.

I think the logic is already in place. What seems to be missing is the continue keyword.

Here's an example:

```rb
count = 0
while true
  count += 1
  if count < 5
    redo
  else
    break
  end
  raise 'should not get here'
end
```

This produces:

```js
  count = 0;
  $a = false; while ($a || $truthy(true)) {
    $a = false;
    count = $rb_plus(count, 1);
    if ($truthy($rb_lt(count, 5))) {
      $a = true
    } else {
      break;
    };
    self.$raise("should not get here");
  };
```

All that's missing for this to work correctly is a `continue` keyword after the `$a = true` assignment

```js
  count = 0;
  $a = false; while ($a || $truthy(true)) {
    $a = false;
    count = $rb_plus(count, 1);
    if ($truthy($rb_lt(count, 5))) {
      $a = true; continue;
    } else {
      break;
    };
    self.$raise("should not get here");
  };
```

**Comment by iliabylich** [comment]
Heh, looks like you are right. `nodes/while.rb:30` is where `continue` should be inserted. Could you (or @Mogztter ) check it please?

**Comment by Mogztter** [comment]
@iliabylich @mojavelinux PR sent :tada:
