### ISSUE TITLE
Globals & Module Constants - suddenly disappear and become 'undefined'.

### ISSUE THREAD

**Issue by mistergibson** [opal/opal#1834]
I'm curious: under what circumstances are globals and module constants undeclared - if only by accident? I usually use a module constant GxG::OBJECT_SPACE as a registry for page objects to be rendered and updated. I push page content via websockets into a rendering/tracking engine without reloading the web page or re-initializing the bootstrap code. It is a simple design. However, for some reason - when I push content to another second page of content into the engine - this central global var (or module constant) is now 'undefined'. it is just GONE - nowhere to be found. Now at no point did I claw-hammer this constant into oblivion as I rely upon it to hold the current display state. I also tested this with a global var and had the *exact* same result. Here is the code that even touches the global $object_space (or usually the constant GxG::OBJECT_SPACE, but its the same either way):

https://gist.github.com/mistergibson/1714d69fc1b6f12419d181769ea3b1e0

**Comment by iliabylich** [comment]
Could you provide any code to reproduce this issue? It's hard to say what's happened and also I've never seen any issue similar to what you've described. Which version of Opal do you use?

**Comment by mistergibson** [comment]
The only code that even touches the global / constant is there in the gist - no other code even touches that global or constant. I'm using Opal 0.11 from the standard gem repo. I tried the github latest once and it blew everything up and so I went back to the std. 0.11 version. Is there going to be a 0.12? I don't think Opal, given this bug, is ready for 1.0. Just say'n. All I do in my code is do a Hash.delete(:key) op and the global undeclares to undefined. too weird.

**Comment by iliabylich** [comment]
`Hash#delete` doesn't touch constants or global variables, so most probably it's a bug somewhere in your code. Could you please provide any steps for reproduction?

**Comment by mistergibson** [comment]
Sure: (based on the gist code)

1.  Opal.eval("$object_space[:registry].keys.each { |k| GxG::unregister(k.to_sym) }"); .... this will empty the registry, and when I check for $object_space I get:

2.  Opal.eval("$object_space.inspect");
TypeError: value is undefined

I *should* get: {:registry => {}}

**Comment by iliabylich** [comment]
I've identified the issue. Your data is still there, in the hash, but `inspect` is broken.

The reason is that `String#to_sym` returns a String object instead of the plain string literal. Later `Hash#delete` uses `===` to find the key and remove it (and of course it fails, because `"string" !== new String("string")`), but `delete hash[key]` removes the k/v pair (because ... that's just how JS works). So the hash becomes broken, it still holds your key, but there's no associated value with it.

The fix is simple, we need to return `self.toString()` from the `String#intern` method which is aliased to `String#to_sym`.

And I believe nobody have reported this issue before because in Opal `Symbol` is actually a `String`. So nobody uses this method.

I'll send a PR soon.
