### ISSUE TITLE
Fundamentals JavaScript objects are altered

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#1846]
```js
require('opal-runtime');
const https = require('https');
```

```
_http_outgoing.js:55
const hasOwnProperty = Function.call.bind(Object.prototype.hasOwnProperty);
                                     ^

TypeError: Cannot read property 'bind' of undefined
    at _http_outgoing.js:55:38
    at NativeModule.compile (internal/bootstrap/loaders.js:235:7)
    at NativeModule.require (internal/bootstrap/loaders.js:155:18)
    at _http_server.js:39:29
    at NativeModule.compile (internal/bootstrap/loaders.js:235:7)
    at NativeModule.require (internal/bootstrap/loaders.js:155:18)
    at https.js:34:5
    at NativeModule.compile (internal/bootstrap/loaders.js:235:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:155:18)
    at Function.Module._load (internal/modules/cjs/loader.js:530:25)
```

The line `const hasOwnProperty = Function.call.bind(Object.prototype.hasOwnProperty);` was added 2 months ago in Node.js 10+

As you can see below, `Function.call` is `undefined` once `opal-runtime` is required:

```js
console.log('Function.call', Function.call); // Function.call function call() { [native code] }
require('opal-runtime');
console.log('Function.call', Function.call); // Function.call undefined
```

In `proc.rb` we define properties on the `Function` object: https://github.com/opal/opal/blob/master/opal/corelib/proc.rb#L2-L3

**Comment by Mogztter** [comment]
For reference, here's the code added in Node.js: https://github.com/nodejs/node/blob/8ab7ea6eed76d069dfd82684e2157e7d88badebf/lib/_http_outgoing.js#L55

**Comment by Mogztter** [comment]
`Function.call` is lost after this call: https://github.com/opal/opal/blob/3c8d93ea8b3ed12b4c49c51cc96d092570c9f64c/opal/corelib/runtime.js#L1161

As a workaround it's possible to define a static method in `proc`:

```rb
def self.call
  `Function.call`
end
```

I don't know why it's needed since `Proc` already extends `Function` :thinking:

**Comment by iliabylich** [comment]
You are absolutely correct, that's a bug. This line initializes a singleton class of the bridged class to make the code like this working:
``` ruby
class Proc < `Function`
end

class Class
  def m
  end
end

Proc.m
```
(Because all singleton classes are inherited from `Class`)

Basically you can reproduce it with any bridged class (Error/Number/String) by setting any field on the `BridgedClass.__proto__`. Bridging removes this property.

Other class fields (like `Error.stackTraceLimit`) are not affected by this bug, they are defined on the `Class`, not on the `Class.__proto__`.

**Comment by iliabylich** [comment]
It's related to bridging. All Opal classes are functions, and all of them don't have `call`/`bind`/`apply` method.

Two options:
1. A simple and incomplete: to copy everything from `Function.prototype` to `Class.prototype`. It's just a few lines of code, but if someone adds more props to `Function.prototype` none of them will be copied to Opal classes.
2. A proper one: classes are functions, so they must have `Function.prototype` somewhere in the prototype chain. But it literally means inheriting from the `Function`, so **every** class will be an instance of `Proc` (because it's bridged to a `Function`). Not sure if it's ok, but that's how it should be in JS. We can document it somewhere in `README.md`, that's basically a breaking change.

**Comment by mojavelinux** [comment]
As @iliabylich points out, this is not limited to Function.call. It also affect Function.apply. I guess all properties of Function.

**Comment by Mogztter** [comment]
A related issue: https://github.com/Mogztter/opal-node-runtime/issues/4
