### ISSUE TITLE
Map ERB#result_with_hash method

### ISSUE THREAD

**Issue by Mogztter** [opal/opal#2031]
I'm using [ERB#compile](https://github.com/opal/opal/blob/f1c093bb946af78403971151ec5fa12b086c6f76/lib/opal/erb.rb#L27) to compile an ERB template to JavaScript:

```js
var result = ERB.compile('The value of x is: <%= x %>')
```

It produces a [Template](https://github.com/opal/opal/blob/f1c093bb946af78403971151ec5fa12b086c6f76/stdlib/template.rb#L26-L28) with a `render` function.
I think it would be useful in JavaScript to implement a function similar to [ERB#result_with_hash](https://ruby-doc.org/stdlib-2.6.5/libdoc/erb/rdoc/ERB.html#method-i-result_with_hash).
This function will be really useful in JavaScript, to call a template with an arbitrary hash:

```js
var toHash = function (object) {
  return object && !object.$$is_hash ? Opal.hash2(Object.keys(object), object) : object
}

Opal.Template['$[]']('(erb)').$render_with_hash(toHash({key: 'value'}))
```

Otherwise I'm not really sure how to call `render` with a custom value for `x`...

**Comment by ahmadine** [comment]
The current render uses instance_eval if an argument is provided. Therefore, you could execute:

```ruby
Template['name'].render({key: 'value'})
```

This would expose this hash as self, so you could do

```erb
<%= self[:key] %>
```

If you wanted to do so that you wouldn't use self, and use variables like x, you could use an OpenStruct (or Struct, or your own object - this is the most common usecase for templates in Ruby).

```ruby
Template['name'].render(OpenStruct.new(x: 'hello'))
```

I don't know if that helps, that's probably not the best JS API out there.

**Comment by Mogztter** [comment]
> The current render uses instance_eval if an argument is provided. Therefore, you could execute:

You are right, I didn't realize that.

> I don't know if that helps, that's probably not the best JS API out there.

No but I think it's fine because most of the time the `render` function will take a Ruby (Opal) instance.
After some consideration, I think it won't be really useful, closing, sorry about that 😅
