### ISSUE TITLE
undefined method `retry' for main

### ISSUE THREAD

**Issue by jeezs** [opal/opal#2041]
Hello it seems retry is unavailable in Opal using begin rescue end.
here is an example of a code that raise an error :

```rb
def wait time
  ` setTimeout(function(){ #{yield} }, #{time});`
end
waiting(1) do 
  a=:my_var
end
begin 
  puts a
rescue
  wait(5) do 
	retry
  end
   puts :to_early
end
```

**Comment by iliabylich** [comment]
yes, Opal compiled `retry` keyword into a method - https://github.com/opal/opal/blob/3c8d93ea8b3ed12b4c49c51cc96d092570c9f64c/lib/opal/nodes/rescue.rb#L189-L195.

Unfortunately, implementing retry is somewhat complicated without using `goto`.

Actually, maybe a block of code with `retry` could be implemented as a loop that runs once by default and `retry` could change some variable used in the loop condition to run the body one more time. I guess it's similar to how Opal users fix it manually 😄

**Comment by ahmadine** [comment]
I think there are two issues here. One, yes, this code works in MRI (creates an infinite loop) and doesn't work in Opal (retry undefined in main):

```ruby
begin
  puts "Hello!"
  nomethod
rescue NameError
  retry
end
```

This code does work in neither and is similar to what @jeezs wants to achieve:

```ruby
begin
  puts "Hello!"
  nomethod
rescue NameError
  1.times { retry }
end
```

So, let's say that calling retry outside of the scope is outside of the scope (pun intended) of this issue. I think this issue can be fixed by... using goto, yes. Javascript supports one particular type of goto:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label

Therefore, we could do it in such a way, that if `retry` is found inside a rescue block, then instead of constructing an exception catching logic in this way:

```js
try { ... } catch(e) { $retry(); }
```

we could construct this code:

```js
rescue_ac3d: while(1) { try { ... } catch(e) { continue rescue_ac3d; } break; }
```

**Comment by ahmadine** [comment]
I don't know how it will interact with the loops though. Anyway, the Opal exception handling logic looks really sub-par to how other parts of Ruby are implemented.
