### ISSUE TITLE
[With patch] optimize readUnicodeCharChunk performance

### ISSUE THREAD

**Issue by Oleksiika** [opal/opal#2129]
![image](https://user-images.githubusercontent.com/55696401/95875121-577e5380-0d7a-11eb-8830-30bd8dc40836.png)

Our tests show that `readUnicodeCharChunk` from `unpack.rb` has a bottleneck ( see screen )
Please consider the patch file I've attached that replaces 
```
bytes = bytes.slice(1, bytes.length);
```
with simple index

[0001-Optimize-readUnicodeCharChunk.patch.zip](https://github.com/opal/opal/files/5372076/0001-Optimize-readUnicodeCharChunk.patch.zip)

**Comment by ghaiklor-wix** [comment]
Pasting the diff here for visibility:

```
From 82cf939d49c29c118a1aeeb480fad05fedca760a Mon Sep 17 00:00:00 2001
From: oleksiika <oleksiika@wix.com>
Date: Tue, 13 Oct 2020 17:31:10 +0300
Subject: [PATCH] Optimize readUnicodeCharChunk

* replace `bytes = bytes.slice(1, bytes.length);` copying with index
---
 opal/corelib/string/unpack.rb | 16 +++++++++-------
 1 file changed, 9 insertions(+), 7 deletions(-)

diff --git a/opal/corelib/string/unpack.rb b/opal/corelib/string/unpack.rb
index 8595d744..a983ab2f 100644
--- a/opal/corelib/string/unpack.rb
+++ b/opal/corelib/string/unpack.rb
@@ -336,9 +336,11 @@ class String
     }
 
     function readUnicodeCharChunk(bytes) {
+      var currentByteIndex = 0;
+      var bytesLength = bytes.length;
       function readByte() {
-        var result = bytes[0];
-        bytes = bytes.slice(1, bytes.length);
+        var result = bytes[currentByteIndex++];
+        bytesLength = bytes.length - currentByteIndex;
         return result;
       }
 
@@ -346,7 +348,7 @@ class String
 
       if (c >> 7 == 0) {
         // 0xxx xxxx
-        return { chunk: [c], rest: bytes };
+        return { chunk: [c], rest: bytes.slice(currentByteIndex) };
       }
 
       if (c >> 6 == 0x02) {
@@ -372,10 +374,10 @@ class String
         #{raise 'malformed UTF-8 character'}
       }
 
-      if (extraLength > bytes.length) {
+      if (extraLength > bytesLength) {
         #{
           expected = `extraLength + 1`
-          given = `bytes.length + 1`
+          given = `bytesLength + 1`
           raise ArgumentError, "malformed UTF-8 character (expected #{expected} bytes, given #{given} bytes)"
         }
       }
@@ -395,12 +397,12 @@ class String
       }
 
       if (result <= 0xffff) {
-        return { chunk: [result], rest: bytes };
+        return { chunk: [result], rest: bytes.slice(currentByteIndex) };
       } else {
         result -= 0x10000;
         var high = ((result >> 10) & 0x3ff) + 0xd800,
             low = (result & 0x3ff) + 0xdc00;
-        return { chunk: [high, low], rest: bytes };
+        return { chunk: [high, low], rest: bytes.slice(currentByteIndex) };
       }
     }
 
-- 
2.23.0
```

**Comment by hmdne** [comment]
In general encoding support in Opal is quite a mess (which it inherits from Javascript, because Javascript among languages is quite odd, because it uses UTF-16. Almost no one notices that unless he has to work with characters over the BMP - ie. >0xffff). There's one issue that basically says, that due to this call it may be impossible under certain circumstances to compile a file with Unicode characters (#2099). We have no good solution for this issue in general at the current time, but there are people working on that (for instance, #2177). I'm thinking about a few possibilities.

Regarding the compile times, I hope this patch helped you approach your performance goal. I would also suggest, that it could be a nice idea to compile those templates using Ruby-MRI.

**Comment by ghaiklor-wix** [comment]
@hmdne in a result we rolled back to 0.9.4 and turns out it works 2-3x times faster and consumes 4x times less memory 🤷

**Comment by hmdne** [comment]
The issue is caused by 6fddca888e04c67192d751c1f6a893b68ac54752 (v1.0.0-237-g6fddca88) which increased compilation times 5-fold (based on my benchmark which I will publish later, as it's very interesting :D). @Oleksiika's patch didn't give us any gains. Before 18be4474 (v0.10.0.beta5-9-g18be4474 - which broke ERB until 0667b7b0 - v0.10.2-115-g0667b7b0) which started using a parser gem, things were even 2.5x faster.

Some interim solution could be to do a shortcut with String#codepoints, but this isn't Encoding-aware. I'm also referencing #2235 where I added this patch and which is about a rework of String#unpack.

Note: all this only concerns JS-compiled Opal.
