### ISSUE TITLE
Strange path: /usr/bin/../exe/opal (LoadError)

### ISSUE THREAD

**Issue by rubyFeedback** [opal/opal#2163]
opal hello_world.js.rb
Traceback (most recent call last):
        1: from /usr/bin/opal:4:in `<main>'
/usr/bin/opal:4:in `load': cannot load such file -- /usr/bin/../exe/opal (LoadError)

I installed via oldschool setup.rb, from the .gem file.

I am aware that this may not be the recommended way to install it, but that
opal wants to be put under exe/ is very very strange. The gems that I know
all prefer bin/ so I am confused why this seems to be a default.

It also seems to depend on bundler - is this necessary? I tend to use 
.gemspec files. Simple things such as:

    require 'opal/opal.rb'

Would be enough.

**Comment by hmdne** [comment]
Can you tell us if your /usr/bin/opal is a symlink or a regular file?

```bash
$ ls -al /usr/bin/opal
```

**Comment by elia** [comment]
We picked up the exe/bin distinction from the bundler gem generator, which does a pretty good job at setting up the gemspec. 

Is this `setup.rb` https://i.loveruby.net/en/projects/setup/?
Anyway I have no objection in accepting PRs to accomodate things so that it's easier to install in a different way, as long as it's not too invasive. About the bundler dependency it depends on it for the gem tasks that are used to prepare and release new versions.

**Comment by elia** [comment]
Closing, @rubyFeedback feel free to reopen/ping if this is still an issue 👍
