### ISSUE TITLE
Infinite loop on scan

### ISSUE THREAD

**Issue by meh** [opal/opal#457]
```ruby
  def self.heredoc(string)
    indent = string.scan(/^[ \t]*(?=\S)/).min.size rescue 0

    string.gsub(/^[ \t]{#{indent}}/, '')
  end
```

This causes an infinite loop on Opal.

**Comment by meh** [comment]
@vais want to give this a shot?

**Comment by vais** [comment]
@meh I'll see what I can do...

The problem is `String#scan` is not being tested at all right now. In `spec/rubyspecs` we have:
```
...
# corelib/core/string/scan_spec - infinite loop on parsing
...
```
And indeed running the following will produce no result other than warming your room a degree or so:
```
$ bundle exec rake mspec_node PATTERN=spec/corelib/core/string/scan_spec.rb
```
So, that's where I'd start, trying to isolate the code in that spec that causes the infinite loop and rip it out. Then make `String#scan` pass the rest of its spec.

As it stands, the code snippet in this issue does not cause an infinite loop for me, but it still does not work correctly because `String#scan` implementation is wrong - specifically, it does not set the multiline flag on the JS regexp for you, which I think it should in order to match Ruby's semantics. But I don't like "fixing" it without having the spec at my back.

**Comment by vais** [comment]
@meh rubyspec is silent on the whole multiline issue, so we likely have other multiline-related bugs we don't know about (sigh), but I fixed the known issues, which is `String#scan`, `String#gsub`, and, albeit unrelated to this specific use case, `String#rindex` and `String#rpartition`.

So, now:
```
$ cat test.rb
def heredoc(string)
  indent = string.scan(/^[ \t]*(?=\S)/).min.size rescue 0
  string.gsub(/^[ \t]{#{indent}}/, '')
end

def test
  s = <<-TEXT
              Level 1
                Level 2
              Level 1
                Level 2
            troll
                  Level 3
  TEXT
  puts s
  puts "-------------------------"
  puts heredoc(s)
end

test
```
```
$ bundle exec opal test.rb 
              Level 1
                Level 2
              Level 1
                Level 2
            troll
                  Level 3
-------------------------
  Level 1
    Level 2
  Level 1
    Level 2
troll
      Level 3
```
