### ISSUE TITLE
method call bug

### ISSUE THREAD

**Issue by shlee322** [opal/opal#679]
The code above is executed successfully in Ruby1.8.
```ruby
def a? (x, y)
    return true
end

puts a? (5,5)
```
but has error in Opal:
```
/lib/opal/nodes/call.rb:43:in `block in default_compile': undefined method `first' for :int:Symbol (NoMethodError)
```

**Comment by adambeynon** [comment]
Im not sure if this was fixed since the last release, but on edge/master (used by the website), it seems to be working ok:

http://opalrb.org/try/#code:def%20a%3F%20(x%2C%20y)%0A%20%20%20%20return%20true%0Aend%0A%0Aputs%20a%3F%20(5%2C5)

Could you confirm which version of Opal you are using though, so we can make sure that it is fixed.

**Comment by shlee322** [comment]
I am using master branch.
```ruby
puts a? (5,5) -> fail
puts a?(5, 5) -> success
```

**Comment by meh** [comment]
```
> ripl
>> def a? (x, y)
|    return true
|  end  
=> :a?
>> puts a? (5, 5)
SyntaxError: (ripl):4: syntax error, unexpected ',', expecting ')'
puts a? (5, 5)
           ^
>> RUBY_VERSION
=> "2.1.5"
```

It shouldn't work on Opal either, we're targeting Ruby 2.x.

**Comment by shlee322** [comment]
oh... sorry;;
