### ISSUE TITLE
native_alias doesn't work for extended objects

### ISSUE THREAD

**Issue by matthewp** [opal/opal#692]
```ruby
class Foo
  native_alias :hello, :hello
end

class Bar < Foo
  def hello
    'hello'
  end
end

bar = Bar.new
`bar.hello()`
```

Should this be possible, and if not is there a good workaround?

**Comment by elia** [comment]
native_alias behavior mimics that of alias (or method_alias)  thus the real problem is that no exception is raised when you try to alias a method that's not yet defined.

To achieve the behavior you want my advice is to define the is method directly in is (via either backlinks or x strings) and if that's something you do often you van extract that into a method, as it's done for native_alias itself. 

If you need help interpolating js and ruby have a look at how it's done in corelib and stdlib first (opal/corelib/ and stdlib/ in this repo) and then feel free to ask in the IRC or gitter channels or in the comments of this issue :)
