### ISSUE TITLE
Class#=== is broken for bridged classes

### ISSUE THREAD

**Issue by adambeynon** [opal/opal#693]
This works:

```ruby
Object === Object #=> true
```

But this does not:

```ruby
Array === Array #=> false
```

:wq

**Comment by Ajedi32** [comment]
This occurs in MRI too. It's not a bug, it's just the way the case equality operator works for classes and modules:

From [the docs for `Module#===`](http://www.ruby-doc.org/core/Module.html#method-i-3D-3D-3D):

> # mod === obj → true or false
>
> Case Equality—Returns true if obj is an instance of mod or one of mod’s descendants. Of limited use for modules, but can be used in case statements to classify objects by class.

So because `Object.class.is_a? Object #=> true`, but `Array.class.is_a? Array #=> false`, `Object === Object` will return true, but `Array === Array` will return false.

**Comment by elia** [comment]
Good catch :)

**Comment by adambeynon** [comment]
Oops :(
