### ISSUE TITLE
Has the dust settled for source maps?

### ISSUE THREAD

**Issue by ylluminarious** [opal/opal#774]
@elia, as I understand it, source maps have not been working for some time and things have shaped up recently thanks to your spearheading some things to get them going again. How can I get source maps working properly with the current master?
I have gotten to a point where I want to be sure that it is working for `opal-phaser` (both for our work and for those who are wanting to use it) and so I need to figure out what to do to get ready to be able to use this again. (Obviously using it in 0.7.1 would be great, but I suspect that I am stuck with `master` until 0.7.2 is released for so that I can define it for the gemspec).

**Comment by jwaldrip** [comment]
:+1: source maps would be a huge win if they were working again. It is making debugging Opal very difficult.

**Comment by elia** [comment]
Yes the, on master they work fine (at least on my projects) as long as you serve assets separately.

my Gemfile (from a rails app) has these lines:

```
gem 'opal-rails',  github: 'opal/opal-rails'
gem 'opal',        github: 'opal/opal'
gem 'opal-haml',   github: 'opal/opal-haml'
gem 'opal-rspec',  github: 'opal/opal-rspec'
gem 'opal-jquery', github: 'opal/opal-jquery'
```

**Comment by ylluminate** [comment]
How close are we to a gem point drop with these working @elia?  I think some of the confusion is that of master having them working and not the most recent release version.  We probably also should write up a quick entry on the docs to give examples of it working along with screenshots to demonstrate what one should expect when they are working since this topic is still causing a lot of confusion and concern.  We're still having arguments with people who are saying Opal's not worth using due to poor debugging facilities and I just have to kind of throw my hands up b/c they're using it as an excuse without digging in.

**Comment by elia** [comment]
Good point, @opal/owners I think we should just release

**Comment by ylluminate** [comment]
So are we about ready to pop this .8 baby out @opal/owners?
