### ISSUE TITLE
Don't have a Code of Conduct

### ISSUE THREAD

**Issue by astrolantique** [opal/opal#945]
HEAR YE HEAR YE
this message was penned by ASTROLANTIQUE on 18/6/2015 at approximately 9:31PM central standard time.

this GitHub(:tm:) issue wishes to enforce the following policy:
1. this is a project for code and not politics

**Comment by HandsomeMatt** [comment]
+1 code should be free

**Comment by Bumrang** [comment]
+2 code should have freedom

**Comment by astrolantique** [comment]
+3 politics are 4 dummies

**Comment by TheBerkin** [comment]
+4 Use C#

**Comment by andrewmcwatters** [comment]
+5 thanks fp

**Comment by matt-attack** [comment]
+6 When did github issue trackers become a place for people track their personal issues?

**Comment by Ajedi32** [comment]
I actually really like this idea by @samzanemesis on the other thread:

> Instead of a code of conduct I propose a set of goals to the project, the Mer Mobile OS project for example gets their goal and what they seek right in the main page, the project is also incredibly well maintained and due to that people get along with other members.

Rather than try to write a bunch of highly specific rules to cover every conceivable situation that might arise, or highly general, subjective rules which don't do anything other than restate common sense, it might be good to simply write a mission statement or some explanation of the goals of this project, and call out behavior within the project that doesn't advance those goals. (For example, political debate has nothing to do with building a Ruby to JavaScript source-to-source compiler, and would therefore fall afoul of the mission statement. Similarly, if someone were to start harassing someone who tried to submit a pull request or such, that would also fall afoul of the project's goals.)

**Comment by cpancake** [comment]
jeez guys calm down it's just a code of conduct

**Comment by Ajedi32** [comment]
@cpancake I think this issue is more a backlash against all the political browbeating going on in the other threads than actual opposition to the idea of a code of conduct in general. That's my impression anyway.

**Comment by puromonogatari** [comment]
A code of conduct is entirely reasonable, if it prevents anyone who has ever contributing code from offending anyone else who also has.

How can pastafarians expect to be protected from bigotry otherwise

**Comment by ciafwywcoc** [comment]
I've written a very appropriate code of conduct. I think it should be implemented by all pen source projects. Stat! ;)
https://github.com/ciafwywcoc/ciafwywcoc/blob/master/CODE_OF_CONDUCT

**Comment by cpancake** [comment]
@ciafwywcoc get over it

**Comment by ciafwywcoc** [comment]
I'm not only over it, I'm all over it. On top of the wold really. :) 

But seeing nether you nor I contributed to Opal yet, I'll just follow my own COC and GTFO. I just hope the unhelpful politically motivated bullies (the POMOB) do the same.
