### ISSUE TITLE
Pass Time.new issue!

### ISSUE THREAD

**Issue by cj** [opal/opal#972]
This commit https://github.com/opal/opal/commit/c55b41b1698489f8b23fa7132d40694d287cf1fa is causing an error when running opal-rspec `TypeError: 'undefined' is not a function (evaluating 'lhs['$-'](rhs)')`.

To recreate, clone https://github.com/opal/opal-rspec.  In the Gemfile, update it to look like this:

```
gem 'opal', github: 'opal/opal', ref: 'c55b41b1698489f8b23fa7132d40694d287cf1fa'
gem 'rspec'
gem 'rspec-support'
gem 'rspec-core'
gem 'rspec-mocks'
gem 'rspec-expectations'
```

run `bundle && bundle exec rake` and you'll see the error.

**Comment by vais** [comment]
@cj in opal/corelib/time.rb, changing:
```ruby
  def self.now
    new
  end
```
to:
```ruby
  def self.now
    `new Date()`
  end
```
fixes the error. @elia I am not familiar with opal-rspec, but from what I have gathered from the ambient noise over time on github and gitter, it's a bit hacky? Otherwise I have no idea why calling a class method from another class method is a problem in this case.

@cj could you turn the fix above into a PR?

**Comment by elia** [comment]
@vais I think it's something they do while measuring time taken, if I get some time I'll dig in to see what's happening (no guarantees tho)

**Comment by vais** [comment]
@elia ok, I [search for Time.now in the opal-rspec repo](https://github.com/opal/opal-rspec/search?utf8=%E2%9C%93&q=Time.now) and maybe [this](https://github.com/opal/opal-rspec/blob/e2290d56ff5147e5a2b96258ef5bdc2b54a9e6af/vendor_lib/rspec/core.rb#L170) is the source of the problem? Not sure what to do with this... I am reluctant to "fix" it in Opal by *not* calling `Time.new` from `Time.now` and simply returning JS `new Date()` instead as shown above because I feel this is a sign of a deeper issue in Opal that we may want to address. I'm open to suggestions if you have any ideas.

**Comment by cj** [comment]
@vais do you still need me to create the pull request?

**Comment by vais** [comment]
@cj not sure - see my comment to @elia above. Whatever rspec is doing should be do-able without making this change to `Time` - it is a sign of another problem in Opal.

**Comment by vais** [comment]
The deeper issue seems to be with either `Module#define_method` or `Method#to_proc` (or both). Here is an example that demonstrates the problem:
```ruby
class Lender
  def self.abc
    p "hi"
  end
  def self.xyz
    p self
    abc
  end
end

module Namespace
  class Borrower
    class << self
      define_method(:xyz, &::Lender.method(:xyz))
    end
  end
end

Namespace::Borrower.xyz
```
Here is what happens when executed on MRI:
```
$ ruby -v test.rb 
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
Lender
"hi"
```
And here is what happens when executed on Opal:
```
$ bundle exec opal -v test.rb 
Opal v0.8.0.rc1
Borrower

/private/var/folders/pt/kr0lwm4d20jgc_jvpc5fyk1r0000gn/T/opal-nodejs-runner-20150711-4423-a92r9:3623
      throw exception;
            ^
NoMethodError: undefined method `abc' for Borrower
```
Note that `self` is different between MRI and Ruby, and that's the cause of the problem. In MRI, `self` still points to the original class from which the method was borrowed (`Lender`). In Opal, `self` points to the class that borrowed the method (`Borrower`).

@elia, @meh I managed to fix this case by making `Method#to_proc` return an anonymous js function that calls `@method` on the `@receiver`. That worked, but it broke some specs. Any ideas on how to fix? I'm not even sure I understand why this works on MRI - by virtue of what umbilical cord does `&::Lender.method(:xyz)` stay connected to the `Lender` class??

**Comment by elia** [comment]
I still forget every time the difference between proc and lambda 😔

Also…

🐢
🐢
🐢
🐢
🐢
🐢
🐢
🐢
🐢
🐢
🐢
🐢

**Comment by Ajedi32** [comment]
@vais 

> by virtue of what umbilical cord does &::Lender.method(:xyz) stay connected to the Lender class?? It's just a lambda after & is executed, it's no longer a bound method.

That's actually not true. See [`Object#method`](http://ruby-doc.org/core/Object.html#method-i-method):

> ## method(sym) → method
>
> Looks up the named method as a receiver in obj, returning a Method object (or raising NameError). The Method object acts as a closure in obj’s object instance, so instance variables and the value of self remain available.
>
> ```ruby
> class Demo
>   def initialize(n)
>     @iv = n
>   end
>   def hello()
>     "Hello, @iv = #{@iv}"
>   end
> end
> 
> k = Demo.new(99)
> m = k.method(:hello)
> m.call   #=> "Hello, @iv = 99"
> 
> l = Demo.new('Fred')
> m = l.method("hello")
> m.call   #=> "Hello, @iv = Fred"
> ```

[UnboundMethod](http://ruby-doc.org/core/UnboundMethod.html) is something entirely different:

> # UnboundMethod
> 
> Ruby supports two forms of objectified methods. Class Method is used to represent methods that are associated with a particular object: these method objects are bound to that object. Bound method objects for an object can be created using Object#method.
> 
> Ruby also supports unbound methods; methods objects that are not associated with a particular object. These can be created either by calling Module#instance_method or by calling unbind on a bound method object. The result of both of these is an UnboundMethod object.
> 
> Unbound methods can only be called after they are bound to an object. That object must be be a kind_of? the method's original class.
> 
> ```ruby
> class Square
>   def area
>     @side * @side
>   end
>   def initialize(side)
>     @side = side
>   end
> end
> 
> area_un = Square.instance_method(:area)
> 
> s = Square.new(12)
> area = area_un.bind(s)
> area.call   #=> 144
> ```
>
> Unbound methods are a reference to the method at the time it was objectified: subsequent changes > to the underlying class will not affect the unbound method.
> 
> ```ruby
> class Test
>   def test
>     :original
>   end
> end
> um = Test.instance_method(:test)
> class Test
>   def test
>     :modified
>   end
> end
> t = Test.new
> t.test            #=> :modified
> um.bind(t).call   #=> :original
> ```

So yeah, pretty complicated...

**Comment by vais** [comment]
@Ajedi32 so, then what does `&::Lender.method(:xyz)` mean, exactly? My understanding is that the `&` prefix is the same as calling `to_proc` on the return value of `method`. Maybe this is where I'm getting confused? Because if it does call `to_proc`, we are no longer dealing with a method object, but with a proc. Hence I do not understand how it still maintains connection to the original class now that it's just a proc... :confused:

**Comment by Ajedi32** [comment]
Well, I'm not very familiar with C or the Ruby code base, but the comment in the source here seems clear enough:

> # to_proc → proc
> 
> Returns a Proc object corresponding to this method.
> 
>  ```c
>                static VALUE
> method_proc(VALUE method)
> {
>     VALUE procval;
>     struct METHOD *meth;
>     rb_proc_t *proc;
>     rb_env_t *env;
> 
>     /*
>      * class Method
>      *   def to_proc
>      *     proc{|*args|
>      *       self.call(*args)
>      *     }
>      *   end
>      * end
>      */
>     TypedData_Get_Struct(method, struct METHOD, &method_data_type, meth);
>     procval = rb_iterate(mlambda, 0, bmcall, method);
>     GetProcPtr(procval, proc);
>     proc->is_from_method = 1;
>     proc->block.self = meth->recv;
>     proc->block.klass = meth->defined_class;
>     GetEnvPtr(proc->envval, env);
>     env->block.self = meth->recv;
>     env->block.klass = meth->defined_class;
>     env->block.iseq = method_get_iseq(meth->me->def);
>     return procval;
> }
> ```

No idea how accurate that is (might not really be an exact equivalent), but seems to me like it's just wrapping `call` in a proc and returning that.

**Comment by vais** [comment]
@Ajedi32 you are more familiar with the Ruby code base than you give yourself credit for :smile: Thanks for pointing this out - makes total sense now! I was actually trying to do something very similar with Opal's `Method#to_proc`, which actually fixed this issue, but broke other specs. Now this gives me some motivation to pursue that line of inquiry further...
