### ISSUE TITLE
attribute named `constructor` in `Class#` causes issues when using `Class#define_method`

### ISSUE THREAD

**Issue by ppibburr** [opal/opal#993]
```ruby
class Foo
  class << self
    attr_accessor :constructor
  end

  define_method :foo do
    next(true);
  end
end

# => TypeError: 'undefined' is not an object (evaluating 'self.$$proto.constructor.prototype['$' + name] = func')

```

**Comment by vais** [comment]
So, in `Module#attr_reader` and `Module#attr_writer` (https://github.com/opal/opal/blob/master/opal/corelib/module.rb#L114), we have this:
```javascript
// initialize the instance variable as nil
proto[name] = nil;
```
Since in this case `name` is `'constructor'`, the code above is the same as `proto['constructor']  = nil;`, which is the same as `proto.constructor = nil;`, which is then followed by:
```javascript
proto.constructor.prototype[id] = body;
```
In other words, we set `proto.constructor` to `nil`, then try to use it by accessing its `prototype` property, which, of course, does not work.

@meh do you think this can be fixed? I.e. in general, given how Opal works, using names of existing properties on the prototype appears to be problematic. This issue is an extreme case, but there are likely other possible cases of unexpected behavior stemming from this. I don't see an easy fix here :confused:

**Comment by elia** [comment]
There's a list of js keywords somewhere which get special treatment (iirc they get a $ appended) and probably an helper in the compiler to automatically detect them. 

Can't check now (from mobile) but would be interesting to see how an ivar named @class or @function is translated.

**Comment by vais** [comment]
Oooh, @elia, when you get a chance to dig around, please post back here!
